/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OneOfSpeechToTextRequestContractInput model module.
 * @module model/OneOfSpeechToTextRequestContractInput
 * @version v1
 */
export default class OneOfSpeechToTextRequestContractInput {
  /**
   * Constructs a new <code>OneOfSpeechToTextRequestContractInput</code>.
   * @alias module:model/OneOfSpeechToTextRequestContractInput
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OneOfSpeechToTextRequestContractInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OneOfSpeechToTextRequestContractInput} obj Optional instance to populate.
   * @return {module:model/OneOfSpeechToTextRequestContractInput} The populated <code>OneOfSpeechToTextRequestContractInput</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfSpeechToTextRequestContractInput();
    }
    return obj;
  }
}
