/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SpeechToTextRequestContract model module.
 * @module model/SpeechToTextRequestContract
 * @version v1
 */
export default class SpeechToTextRequestContract {
  /**
   * Constructs a new <code>SpeechToTextRequestContract</code>.
   * @alias module:model/SpeechToTextRequestContract
   * @class
   * @param model {String} 
   * @param dtype {String} 
   * @param input {Object} 
   */
  constructor(model, dtype, input) {
    this.model = model;
    this.dtype = dtype;
    this.input = input;
  }

  /**
   * Constructs a <code>SpeechToTextRequestContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SpeechToTextRequestContract} obj Optional instance to populate.
   * @return {module:model/SpeechToTextRequestContract} The populated <code>SpeechToTextRequestContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SpeechToTextRequestContract();
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('dtype'))
        obj.dtype = ApiClient.convertToType(data['dtype'], 'String');
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], Object);
      if (data.hasOwnProperty('return_timestamps'))
        obj.returnTimestamps = ApiClient.convertToType(data['return_timestamps'], 'String');
      if (data.hasOwnProperty('stream'))
        obj.stream = ApiClient.convertToType(data['stream'], 'Boolean');
      if (data.hasOwnProperty('chunk_length_s'))
        obj.chunkLengthS = ApiClient.convertToType(data['chunk_length_s'], 'Number');
      if (data.hasOwnProperty('stride_length_s'))
        obj.strideLengthS = ApiClient.convertToType(data['stride_length_s'], 'Number');
      if (data.hasOwnProperty('force_full_sequences'))
        obj.forceFullSequences = ApiClient.convertToType(data['force_full_sequences'], 'Boolean');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('task'))
        obj.task = ApiClient.convertToType(data['task'], 'String');
      if (data.hasOwnProperty('num_frames'))
        obj.numFrames = ApiClient.convertToType(data['num_frames'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} model
 */
SpeechToTextRequestContract.prototype.model = undefined;

/**
 * @member {String} dtype
 */
SpeechToTextRequestContract.prototype.dtype = undefined;

/**
 * @member {Object} input
 */
SpeechToTextRequestContract.prototype.input = undefined;

/**
 * @member {String} returnTimestamps
 */
SpeechToTextRequestContract.prototype.returnTimestamps = undefined;

/**
 * @member {Boolean} stream
 */
SpeechToTextRequestContract.prototype.stream = undefined;

/**
 * @member {Number} chunkLengthS
 */
SpeechToTextRequestContract.prototype.chunkLengthS = undefined;

/**
 * @member {Number} strideLengthS
 */
SpeechToTextRequestContract.prototype.strideLengthS = undefined;

/**
 * @member {Boolean} forceFullSequences
 */
SpeechToTextRequestContract.prototype.forceFullSequences = undefined;

/**
 * @member {String} language
 */
SpeechToTextRequestContract.prototype.language = undefined;

/**
 * @member {String} task
 */
SpeechToTextRequestContract.prototype.task = undefined;

/**
 * @member {Number} numFrames
 */
SpeechToTextRequestContract.prototype.numFrames = undefined;

