/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Chunk from './Chunk';

/**
 * The STTChunk model module.
 * @module model/STTChunk
 * @version v1
 */
export default class STTChunk {
  /**
   * Constructs a new <code>STTChunk</code>.
   * @alias module:model/STTChunk
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>STTChunk</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/STTChunk} obj Optional instance to populate.
   * @return {module:model/STTChunk} The populated <code>STTChunk</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new STTChunk();
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
      if (data.hasOwnProperty('chunks'))
        obj.chunks = ApiClient.convertToType(data['chunks'], [Chunk]);
    }
    return obj;
  }
}

/**
 * @member {String} text
 */
STTChunk.prototype.text = undefined;

/**
 * @member {Array.<module:model/Chunk>} chunks
 */
STTChunk.prototype.chunks = undefined;

