/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TextGenerationResponse model module.
 * @module model/TextGenerationResponse
 * @version v1
 */
export default class TextGenerationResponse {
  /**
   * Constructs a new <code>TextGenerationResponse</code>.
   * @alias module:model/TextGenerationResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TextGenerationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TextGenerationResponse} obj Optional instance to populate.
   * @return {module:model/TextGenerationResponse} The populated <code>TextGenerationResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TextGenerationResponse();
      if (data.hasOwnProperty('generatedText'))
        obj.generatedText = ApiClient.convertToType(data['generatedText'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} generatedText
 */
TextGenerationResponse.prototype.generatedText = undefined;

