/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TextToSpeechRequestContract model module.
 * @module model/TextToSpeechRequestContract
 * @version v1
 */
export default class TextToSpeechRequestContract {
  /**
   * Constructs a new <code>TextToSpeechRequestContract</code>.
   * @alias module:model/TextToSpeechRequestContract
   * @class
   * @param model {String} 
   * @param dtype {String} 
   * @param input {String} 
   */
  constructor(model, dtype, input) {
    this.model = model;
    this.dtype = dtype;
    this.input = input;
  }

  /**
   * Constructs a <code>TextToSpeechRequestContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TextToSpeechRequestContract} obj Optional instance to populate.
   * @return {module:model/TextToSpeechRequestContract} The populated <code>TextToSpeechRequestContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TextToSpeechRequestContract();
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('dtype'))
        obj.dtype = ApiClient.convertToType(data['dtype'], 'String');
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], 'String');
      if (data.hasOwnProperty('voice'))
        obj.voice = ApiClient.convertToType(data['voice'], 'String');
      if (data.hasOwnProperty('stream'))
        obj.stream = ApiClient.convertToType(data['stream'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} model
 */
TextToSpeechRequestContract.prototype.model = undefined;

/**
 * @member {String} dtype
 */
TextToSpeechRequestContract.prototype.dtype = undefined;

/**
 * @member {String} input
 */
TextToSpeechRequestContract.prototype.input = undefined;

/**
 * @member {String} voice
 */
TextToSpeechRequestContract.prototype.voice = undefined;

/**
 * @member {Boolean} stream
 */
TextToSpeechRequestContract.prototype.stream = undefined;

