/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TranslationResponse model module.
 * @module model/TranslationResponse
 * @version v1
 */
export default class TranslationResponse {
  /**
   * Constructs a new <code>TranslationResponse</code>.
   * @alias module:model/TranslationResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TranslationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TranslationResponse} obj Optional instance to populate.
   * @return {module:model/TranslationResponse} The populated <code>TranslationResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TranslationResponse();
      if (data.hasOwnProperty('translatedText'))
        obj.translatedText = ApiClient.convertToType(data['translatedText'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} translatedText
 */
TranslationResponse.prototype.translatedText = undefined;

