/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TranslationRequestContract model module.
 * @module model/TranslationRequestContract
 * @version v1
 */
export default class TranslationRequestContract {
  /**
   * Constructs a new <code>TranslationRequestContract</code>.
   * @alias module:model/TranslationRequestContract
   * @class
   * @param model {String} 
   * @param dtype {String} 
   * @param input {String} 
   * @param srcLang {String} 
   * @param tgtLang {String} 
   */
  constructor(model, dtype, input, srcLang, tgtLang) {
    this.model = model;
    this.dtype = dtype;
    this.input = input;
    this.srcLang = srcLang;
    this.tgtLang = tgtLang;
  }

  /**
   * Constructs a <code>TranslationRequestContract</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TranslationRequestContract} obj Optional instance to populate.
   * @return {module:model/TranslationRequestContract} The populated <code>TranslationRequestContract</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TranslationRequestContract();
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('dtype'))
        obj.dtype = ApiClient.convertToType(data['dtype'], 'String');
      if (data.hasOwnProperty('input'))
        obj.input = ApiClient.convertToType(data['input'], 'String');
      if (data.hasOwnProperty('srcLang'))
        obj.srcLang = ApiClient.convertToType(data['srcLang'], 'String');
      if (data.hasOwnProperty('tgtLang'))
        obj.tgtLang = ApiClient.convertToType(data['tgtLang'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} model
 */
TranslationRequestContract.prototype.model = undefined;

/**
 * @member {String} dtype
 */
TranslationRequestContract.prototype.dtype = undefined;

/**
 * @member {String} input
 */
TranslationRequestContract.prototype.input = undefined;

/**
 * @member {String} srcLang
 */
TranslationRequestContract.prototype.srcLang = undefined;

/**
 * @member {String} tgtLang
 */
TranslationRequestContract.prototype.tgtLang = undefined;

