/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TTSResponse model module.
 * @module model/TTSResponse
 * @version v1
 */
export default class TTSResponse {
  /**
   * Constructs a new <code>TTSResponse</code>.
   * @alias module:model/TTSResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TTSResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TTSResponse} obj Optional instance to populate.
   * @return {module:model/TTSResponse} The populated <code>TTSResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TTSResponse();
      if (data.hasOwnProperty('audio'))
        obj.audio = ApiClient.convertToType(data['audio'], 'String');
      if (data.hasOwnProperty('format'))
        obj.format = ApiClient.convertToType(data['format'], 'String');
      if (data.hasOwnProperty('sample_rate'))
        obj.sampleRate = ApiClient.convertToType(data['sample_rate'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} audio
 */
TTSResponse.prototype.audio = undefined;

/**
 * @member {String} format
 */
TTSResponse.prototype.format = undefined;

/**
 * @member {Number} sampleRate
 */
TTSResponse.prototype.sampleRate = undefined;

