/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WoolballAiNetworkApi);
  }
}(this, function(expect, WoolballAiNetworkApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TextToSpeechRequestContract', function() {
      beforeEach(function() {
        instance = new WoolballAiNetworkApi.TextToSpeechRequestContract();
      });

      it('should create an instance of TextToSpeechRequestContract', function() {
        // TODO: update the code to test TextToSpeechRequestContract
        expect(instance).to.be.a(WoolballAiNetworkApi.TextToSpeechRequestContract);
      });

      it('should have the property model (base name: "model")', function() {
        // TODO: update the code to test the property model
        expect(instance).to.have.property('model');
        // expect(instance.model).to.be(expectedValueLiteral);
      });

      it('should have the property dtype (base name: "dtype")', function() {
        // TODO: update the code to test the property dtype
        expect(instance).to.have.property('dtype');
        // expect(instance.dtype).to.be(expectedValueLiteral);
      });

      it('should have the property input (base name: "input")', function() {
        // TODO: update the code to test the property input
        expect(instance).to.have.property('input');
        // expect(instance.input).to.be(expectedValueLiteral);
      });

      it('should have the property voice (base name: "voice")', function() {
        // TODO: update the code to test the property voice
        expect(instance).to.have.property('voice');
        // expect(instance.voice).to.be(expectedValueLiteral);
      });

      it('should have the property stream (base name: "stream")', function() {
        // TODO: update the code to test the property stream
        expect(instance).to.have.property('stream');
        // expect(instance.stream).to.be(expectedValueLiteral);
      });

    });
  });

}));
