/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WoolballAiNetworkApi);
  }
}(this, function(expect, WoolballAiNetworkApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TextGenerationResponse', function() {
      beforeEach(function() {
        instance = new WoolballAiNetworkApi.TextGenerationResponse();
      });

      it('should create an instance of TextGenerationResponse', function() {
        // TODO: update the code to test TextGenerationResponse
        expect(instance).to.be.a(WoolballAiNetworkApi.TextGenerationResponse);
      });

      it('should have the property generatedText (base name: "generatedText")', function() {
        // TODO: update the code to test the property generatedText
        expect(instance).to.have.property('generatedText');
        // expect(instance.generatedText).to.be(expectedValueLiteral);
      });

    });
  });

}));
