/*
 * Woolball AI Network API
 * **Transform idle browsers into a powerful distributed AI inference network**  For detailed examples and model lists, visit our [GitHub repository](https://github.com/woolball-xyz/woolball-server).
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Chunk from './model/Chunk';
import OneOfSpeechToTextRequestContractInput from './model/OneOfSpeechToTextRequestContractInput';
import STTChunk from './model/STTChunk';
import SpeechToTextRequestContract from './model/SpeechToTextRequestContract';
import TTSResponse from './model/TTSResponse';
import TextGenerationRequestContract from './model/TextGenerationRequestContract';
import TextGenerationResponse from './model/TextGenerationResponse';
import TextToSpeechRequestContract from './model/TextToSpeechRequestContract';
import TranslationRequestContract from './model/TranslationRequestContract';
import TranslationResponse from './model/TranslationResponse';
import SpeechRecognitionApi from './api/SpeechRecognitionApi';
import TextGenerationApi from './api/TextGenerationApi';
import TextToSpeechApi from './api/TextToSpeechApi';
import TranslationApi from './api/TranslationApi';

/**
* Transform_idle_browsers_into_a_powerful_distributed_AI_inference_networkFor_detailed_examples_and_model_lists_visit_our__GitHub_repository_httpsgithub_comwoolball_xyzwoolball_server_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var WoolballAiNetworkApi = require('index'); // See note below*.
* var xxxSvc = new WoolballAiNetworkApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new WoolballAiNetworkApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new WoolballAiNetworkApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new WoolballAiNetworkApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Chunk model constructor.
     * @property {module:model/Chunk}
     */
    Chunk,

    /**
     * The OneOfSpeechToTextRequestContractInput model constructor.
     * @property {module:model/OneOfSpeechToTextRequestContractInput}
     */
    OneOfSpeechToTextRequestContractInput,

    /**
     * The STTChunk model constructor.
     * @property {module:model/STTChunk}
     */
    STTChunk,

    /**
     * The SpeechToTextRequestContract model constructor.
     * @property {module:model/SpeechToTextRequestContract}
     */
    SpeechToTextRequestContract,

    /**
     * The TTSResponse model constructor.
     * @property {module:model/TTSResponse}
     */
    TTSResponse,

    /**
     * The TextGenerationRequestContract model constructor.
     * @property {module:model/TextGenerationRequestContract}
     */
    TextGenerationRequestContract,

    /**
     * The TextGenerationResponse model constructor.
     * @property {module:model/TextGenerationResponse}
     */
    TextGenerationResponse,

    /**
     * The TextToSpeechRequestContract model constructor.
     * @property {module:model/TextToSpeechRequestContract}
     */
    TextToSpeechRequestContract,

    /**
     * The TranslationRequestContract model constructor.
     * @property {module:model/TranslationRequestContract}
     */
    TranslationRequestContract,

    /**
     * The TranslationResponse model constructor.
     * @property {module:model/TranslationResponse}
     */
    TranslationResponse,

    /**
    * The SpeechRecognitionApi service constructor.
    * @property {module:api/SpeechRecognitionApi}
    */
    SpeechRecognitionApi,

    /**
    * The TextGenerationApi service constructor.
    * @property {module:api/TextGenerationApi}
    */
    TextGenerationApi,

    /**
    * The TextToSpeechApi service constructor.
    * @property {module:api/TextToSpeechApi}
    */
    TextToSpeechApi,

    /**
    * The TranslationApi service constructor.
    * @property {module:api/TranslationApi}
    */
    TranslationApi
};
